name: Minecraft Server

on:
  workflow_dispatch:

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jre-headless screen

      - name: Download Minecraft Server
        run: |
          mkdir -p minecraft-server
          cd minecraft-server
          curl -o server.jar https://piston-data.mojang.com/v1/objects/dfab8d51e0f6e1a53a0954b9b1eaae1b4044b218/server.jar
          echo "eula=true" > eula.txt

      - name: Start Minecraft Server
        run: |
          cd minecraft-server
          screen -dmS mc_server java -Xmx2G -Xms2G -jar server.jar nogui

      - name: Keep Server Running
        run: sleep 3600
