name: TEST Windows 11 RDP

on: push

jobs:
  windows11-job:
    runs-on: windows-11
    steps:
      - name: Display Windows Version
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
